### ISSUE TITLE
Cannot find problemMatcher when isBackground: true

### ISSUE THREAD

**Issue by Skrypt** [Trottero/dotnet-watch-attach#1]
![image](https://user-images.githubusercontent.com/3228637/146151551-f81d5293-c986-4dbc-9ddb-00eb8b0d86b4.png)

![image](https://user-images.githubusercontent.com/3228637/146151403-132876d6-7453-4a79-bac3-25ea580202c0.png)

I'm trying to implement your solution in Orchard Core project. So far it's working but I'm getting this small issue when I try to start the launcher on the project. When I remove the `"isBackground": true,` it finds the proper problemMatcher but else it shows me this modal that requires me to click "debug anyway" every time. But everything works apart from that.

Let me know if you have an idea. Thanks.

See : https://github.com/OrchardCMS/OrchardCore/pull/10881

**Comment by Trottero** [comment]
I don't have a proper fix for this yet, it is still on my TODOs. A work around for now would be to tick the "Remember my choice for this task" and then clicking Debug Anyway.

I think it has to do with the way the $msCompile matcher works with background tasks

**Comment by mdowais** [comment]
After a few attempts, this seems to work.

`{
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "isBackground": true,
            "args": [
                "watch",
                "run",
            ],
            "problemMatcher": {
                "base": "$msCompile",
                "background": {
                    "beginsPattern": {
                        "regexp": "Building...(.+)?|File changed:(.+)?"
                    },
                    "endsPattern": {
                        "regexp": "Application started|Hot reload of changes succeeded."
                    }
                }
            }
        },`

**Comment by mdowais** [comment]
but problem matcher is not working properly maybe,,

**Comment by Skrypt** [comment]
I tried what you are suggesting in Orchard Core and I had no success with the problem matcher. Still have the same issue. I'm not sure if I should invest time finding a solution for that or wait on the VS Code team to implement it directly in VS Code. To me, using this extension right now this is the best compromise.

**Comment by Trottero** [comment]
@mdowais @Skrypt 

Thanks a lot for your efforts! I've updated the extension so it is no longer neccesary to use `"isBackground": true` in your tasks. `dotnetwatchattach` can now be configured to manage the lifetime of a task by setting the task property in the debug configuration. The example repository and readme have been updated to reflect this change. Feel free to reopen this issue if this doesn't fix the problem.
