### ISSUE TITLE
Configuring dotnet watch attach for dotnetify

### ISSUE THREAD

**Issue by parksj10** [Trottero/dotnet-watch-attach#10]
I've added this to `launch.json`:

```json
{
  "type": "dotnetwatchattach",
  "request": "launch",
  "name": ".NET Watch Attach",
  "args": { // Args to pass to coreclr attach
    "env": {
      "ASPNETCORE_ENVIRONMENT": "Development"
    },
    "project": "${workspaceFolder}/src/UI/FluxusApp/FluxusApp.csproj",
  },
  "task": "watchtask", // Label of watch task in tasks.json
  "program": "FluxusApp" // for windows Or "<startup-project-name>" for linux
}
```

and to `tasks.json`

```json
{
  "label": "watchtask",
  "command": "dotnet",
  "type": "process",
   "linux": {
    "options": {
      "env": {
        // The FileSystemWatcher used by default wasnt working for me on linux, so I switched to the polling watcher.
        "DOTNET_USE_POLLING_FILE_WATCHER": "true"
      }
    }
  },
  "args": [
    "watch",
    "run",
    "${workspaceFolder}/src/UI/FluxusApp/FluxusApp.csproj",
    "/property:GenerateFullPaths=true",
    "/consoleloggerparameters:NoSummary"
  ],
  "problemMatcher": "$msCompile"
}
```

Yet I get the following error:
`watch : Could not find a MSBuild project file in '/Users/josh/Code/RND/fcc'. Specify which project to use with the --project option.`

Note on an M1 Mac, which seems to have added support in this extension

**Comment by Trottero** [comment]
This seems to be an issue with your configuration of the `watchtask` being improperly configured. (the plugin itself hasn't done anything at this point) The task refers to the `${workspaceFolder}` variable which expands to the current folder that is opened in vscode.

Your error seems to use a completely different path than the one configured, what is the current folder that you have open? Also, could you run the `watchtask` seperately without the plugin? (ctrl + alt + T) and select `watchtask`.

**Comment by parksj10** [comment]
worked when I updated the json to following:

```json
{
    "label": "watchtask",
    "command": "dotnet",
    "type": "process",
     "linux": {
      "options": {
        "env": {
          "DOTNET_USE_POLLING_FILE_WATCHER": "true"
        }
      }
    },
    "args": [
      "watch",
      "run",
      "--project",
      "${workspaceFolder}/src/UI/FluxusApp/FluxusApp.csproj",
      "/property:GenerateFullPaths=true",
      "/consoleloggerparameters:NoSummary"
    ],
    "problemMatcher": "$msCompile"
  }
```

**Comment by parksj10** [comment]
However, is the process supposed to terminate and restart? it seems whenever I make a code change I get the following error and everything restarts? 

```
[HPM] Error occurred while proxying request localhost:3000/dotnetify?id=DP5USQdJML86WCo0bdjYMQ&_=1666120490315 to https://localhost:7151/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)

watch : Exited
watch : File changed: /Users/josh/Code/RND/fcc/src/UI/FluxusApp/ViewModels/MainRegion/StartRun/Dialogs/LoadCartridgeDialogVM.cs
watch : Started
```

This seems project specific....

**Comment by Trottero** [comment]
@parksj10 What .NET version are you using? I know they've been working on the watch / hot reload experience, which might be the reason that you see a difference in behavior here.

The older version of watch would watch for any file changes, kill the process and then respawn it, this detaches the debugger as the underlying process (that it is attached to) is killed. I am unsure if the version that you are currently using is doing that too.

During the development of .NET 6 they had hot reloading enabled in some of the earlier previews, and disabled it in later previews. I am not sure if it made it into .NET 6 or if it's already in .NET 7

In any case, you can use any task as the `watchtask` as long as it spawns a dotnet process. (so in your case you can just remove the run argument)

**Comment by parksj10** [comment]
@Trottero, yes we're using .NET 6, and indeed, they do have hot reload incorporated into it.

When I try to remove the `run` task, I get the following error

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/property:GenerateFullPaths=true does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet...
```

**Comment by Trottero** [comment]
@parksj10 Oh, with just `dotnet watch` you really meant just `dotnet watch`. in that case you can remove everything except the `"watch"` arg to mimic that behaviour

**Comment by parksj10** [comment]
It runs (don't hit breakpoints) when I alter to

```
{
  "label": "watchtask",
  "command": "dotnet",
  "type": "process",
      "linux": {
      "options": {
      "env": {
          "DOTNET_USE_POLLING_FILE_WATCHER": "true"
      }
      }
  },
  "args": [
      "watch",
      "--project",
      "${workspaceFolder}/src/UI/FluxusApp/FluxusApp.csproj",
  ],
  "problemMatcher": "$msCompile"
}
```

however, it still tries to exit/reload

```
watch : File changed: /Users/josh/Code/RND/fcc/src/UI/FluxusApp/ViewModels/MainRegion/StartRun/Dialogs/LoadCartridgeDialogVM.cs.
watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
```

**Comment by Trottero** [comment]
I get the same behavior where it still wants to restart when making changes, looks like the hot reload functionality isn't super great yet. If I were you I would accept that the application restarts every time you make a change - the plugin is designed for this after all ;)

As for your breakpoints not being hit, try using the launch config that I posted a little bit earlier, see if you can get it to attach without it reloading (note that the `coreclr` debugger will terminate if you reload the application)

**Comment by parksj10** [comment]
@Trottero, I can get the debugger to attach with your suggested `launch.json` `attach` addition, however, it still trying restart and throwing errors because of the proxy...

```
[HPM] Error occurred while proxying request localhost:3000/dotnetify?id=RN4JUud7I8HAGywttz0iUA&_=1666122836345 to https://localhost:7151/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by parksj10** [comment]
I guess I would note that running `dotnet watch --project /Users/josh/Code/RND/fcc/src/UI/FluxusApp/FluxusApp.csproj` was working for hot reload before, but now is erroring with the following (and asking for restart)

```
[HPM] ECONNRESET: Error: socket hang up
    at connResetException (node:internal/errors:704:14)
    at TLSSocket.socketOnEnd (node:_http_client:505:23)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET'
}
[HPM] Error occurred while proxying request localhost:3000/dotnetify?id=Pahbhf8f_f0B00TpSdBmZw&_=1666123115281 to https://localhost:7151/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by Trottero** [comment]
Judging from the URL in your error message this seems to be an issue related to `dotnetify` which I guess is the framework that you are using to develop your app? I've personally never worked with it, so I don't quite know how it behaves. My guess is that the makers never intended it to be used in combination with the `dotnet watch` command. Even if you manage to fix your hot reloading issue, it's not a permanent fix as some changes do require your application to be restarted, which would result in the same error you are seeing now.

**Comment by parksj10** [comment]
I'm sure we're using .NET 6, however this seems to be a limitation of hotreload/vscode implementation for .NET 6... I guess I'm stuck with the restart, unfortunately (re-navigating the UI is a pain...)

Thanks for all the help, I really appreciate it!

**Comment by Trottero** [comment]
I am sorry that you are going to have to stick to not having hot-reloading now, I've made an example repository incase there are other people who are looking to use dotnetify in combination with the plugin. If you encounter any issues, feel free to open another issue.

[Repository](https://github.com/Trottero/dotnet-watch-attach-dotnetify)
