### ISSUE TITLE
No process with the specified name is currently running.

### ISSUE THREAD

**Issue by kzhui125** [Trottero/dotnet-watch-attach#12]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/11925432/226111367-7672f1b0-a0a4-47eb-a445-3eccd11b0922.png">

it seem the extension not waiting the dotnet watch restart

**Comment by Trottero** [comment]
What does your config look like (`launch.json` and `tasks.json`) this looks like an error from the standard .NET debugger.

**Comment by kzhui125** [comment]
```json
{
        "name": "Watch BlazorServer",
        "type": "dotnetwatchattach",
        "request": "launch",
        "args": {
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
        },
        "task": "watchBlazorServer",
        "program": "BlazorServer"
    }
```

```json
{
    "label": "watchBlazorServer",
    "command": "dotnet",
    "type": "process",
    "linux": {
        "options": {
            "env": {
                "DOTNET_USE_POLLING_FILE_WATCHER": "true"
            }
        }
    },
    "args": [
        "watch",
        "run",
        "${workspaceFolder}/Local/BlazorServer/BlazorServer.csproj",
        "/property:GenerateFullPaths=true",
        "/consoleloggerparameters:NoSummary",
        "--project",
        "${workspaceFolder}/Local/BlazorServer/BlazorServer.csproj"
    ],
    "presentation": {
        "reveal": "never",
        "panel": "dedicated"
    },
    "problemMatcher": "$msCompile"
}
```

**Comment by kzhui125** [comment]
[record.zip](https://github.com/Trottero/dotnet-watch-attach/files/11008840/record.zip)
@Trottero this is the screen recording, thanks.

**Comment by Trottero** [comment]
Your configuration looks fine! It looks like the plugin thinks that your application is already running - which causes this issue with the underlying debugger. Could you maybe launch your watch task (or just run the debug configuration) and do `ps -aco command` in another terminal? This should give us some insight as to what other processes are running that it could maybe confuse with the right one.

**Comment by kzhui125** [comment]
hello @Trottero this is recorded:

![record](https://user-images.githubusercontent.com/11925432/226116083-24c7e64c-3734-40c6-afa9-1039093d37d7.gif)

**Comment by Trottero** [comment]
Could you try renaming your task and your launch configuration? Maybe it is picking those up instead of the process its supposed to.

If possible could you share the project that you have issues with? It would really help if I could reproduce it. It could be a mac only issue, but it needs fixing regardless.

**Comment by kzhui125** [comment]
<img width="1693" alt="image" src="https://user-images.githubusercontent.com/11925432/226122852-c7ad40a5-c08c-4f01-93d7-e1fa54b227f9.png">

I have tried using windows to connect , it has error too.

may be it's a problem of wsl2?

it's a private company repo, thanks for your help

**Comment by kzhui125** [comment]
I have copied the repo to my Mac, to my Windows, and to another debian server.

Mac & Windows works, the debian server and the wsl2 debian server doesn't work.

**Comment by kzhui125** [comment]
I have created a new blazor server project, and it doesn't work.
So I think it will no help if I share my repo.

Is there any other steps to investigate this issue? thanks a lot.

![record2](https://user-images.githubusercontent.com/11925432/226126364-cea0d18a-6362-453a-b2fe-1ac5a3f5a572.gif)

**Comment by Trottero** [comment]
I was able to reproduce the issue (in WSL2 - Ubuntu), have not been able to find a solution yet, going to look at it once I have the time.

I'll keep you posted!

**Comment by kzhui125** [comment]
Great! Thanks a lot.

**Comment by kzhui125** [comment]
works now, thanks 👍
