### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by Trottero** [Trottero/dotnet-watch-attach#5]
Sorry - it's taken so long to get back to you. I should point out, I'm on a Mac so we are not using .exe programs. The program _EPBC.PSAS.dll_ is running after launching _dotnetwatchattach_. 
I have verified this by starting _dotnetwatchattach_ with program commented out, which gives the error. "_Cannot find a program to debug_". 
However, with program not commented out and _dotnetwatchattach_ running, my breakpoints become unbound.

_Originally posted by @dfdumaresq in https://github.com/Trottero/dotnet-watch-attach/issues/4#issuecomment-1171515302_

**Comment by Trottero** [comment]
The plugin is untested on Mac, as I do not own one myself. If I have the time I could attempt to find a service which could provide me with a VM.

`dotnetwatchattach` uses some OS specific commands to get the current list of running programs, there should be a linux ready implementation, but it is also untested. It does a quick check before attaching to said program in order to check if it is actually running.

It might be worth trying to set program to `EPBC.PSAS.dll`, as a similar structure was used for  projects<.NET 5.0.

**Comment by loganbenjamin** [comment]
I've created a pull request for mac support #8 

Works on my M1 Mac running standard .Net 6.0 apps

**Comment by Trottero** [comment]
Great, thank you! Could you post the exact output of the command that you added? Ideally while a dotnet program is running using dotnet watch - Really happy to see you created a PR though!

**Comment by loganbenjamin** [comment]
No worries, this is a great extension you've made!

In the below screenshot I ran `ps -aco command` before and after I started `dotnet watch`.
You can see there is 3 new `dotnet` commands and one `Hello.World` (the name of my app).
![image](https://user-images.githubusercontent.com/34728713/188509382-3226cb9e-ef5d-4498-bcbf-ae08f300ecf8.png)

**Comment by Trottero** [comment]
Looks good to me - On more thing though, would you mind checking if it works with project names longer than 16 characters? Was having some issues with the linux version as the `ps` command would only show the first couple of characters.

**Comment by loganbenjamin** [comment]
Yes, it works with a project I have that has 24 characters

**Comment by Trottero** [comment]
The update is currently rolling out, thank you for your contribution :)

🎉
